env:
  es6: true
  serviceworker: true
  webextensions: true
extends: 'eslint:recommended'
globals:
  # false to disallow overwriting
  globalThis: false
parserOptions:
  ecmaVersion: 2017
  # strict mode
  sourceType: module
rules:
  array-callback-return: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  consistent-this:
    - error
    - self
  curly: error
  dot-notation: error
  eol-last: error
  indent:
    - error
    - 2
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  new-cap: error
  no-array-constructor: error
  no-bitwise: error
  no-caller: error
  no-eval: error
  no-implied-eval: error
  no-iterator: error
  no-loop-func: error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-proto: error
  no-script-url: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-tabs: error
  no-trailing-spaces: error
  no-unused-expressions: error
  semi: error
  space-before-blocks: error
  space-in-parens: error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
